from app.models import db, Like, environment, SCHEMA


def seed_likes():
    likes = [
        Like(
            user_id=1,
            story_id=1,
            count=3
        ),
        Like(
            user_id=2,
            story_id=1,
            count=1
        ),
        Like(
            user_id=2,
            story_id=2,
            count=4
        ),
        Like(
            user_id=4,
            story_id=1,
            count=40
        ),
        Like(
            user_id=3,
            story_id=2,
            count=5
        ),
        Like(
            user_id=4,
            story_id=3,
            count=5
        ),
        Like(
            user_id=4,
            story_id=5,
            count=2
        ),
        Like(
            user_id=5,
            story_id=6,
            count=19
        ),
        Like(
            user_id=6,
            story_id=2,
            count=12
        ),
        Like(
            user_id=7,
            story_id=3,
            count=1
        ),
        Like(
            user_id=7,
            story_id=4,
            count=5
        ),
        Like(
            user_id=7,
            story_id=5,
            count=5
        ),
        Like(
            user_id=8,
            story_id=5,
            count=3
        ),
        Like(
            user_id=8,
            story_id=7,
            count=5
        ),
        Like(
            user_id=8,
            story_id=8,
            count=6
        ),
        Like(
            user_id=9,
            story_id=7,
            count=6
        ),
        Like(
            user_id=9,
            story_id=9,
            count=2
        ),
        Like(
            user_id=9,
            story_id=10,
            count=2
        ),
        Like(
            user_id=10,
            story_id=9,
            count=2
        ),
        Like(
            user_id=10,
            story_id=7,
            count=2
        ),
        Like(
            user_id=10,
            story_id=4,
            count=4
        ),
        Like(
            user_id=10,
            story_id=14,
            count=4
        ),
        Like(
            user_id=10,
            story_id=11,
            count=7
        ),
        Like(
            user_id=11,
            story_id=11,
            count=2
        ),
        Like(
            user_id=11,
            story_id=12,
            count=6
        ),
        Like(
            user_id=11,
            story_id=13,
            count=9
        ),
        Like(
            user_id=12,
            story_id=11,
            count=3
        ),
        Like(
            user_id=12,
            story_id=5,
            count=3
        ),
        Like(
            user_id=12,
            story_id=8,
            count=8
        ),
        Like(
            user_id=13,
            story_id=1,
            count=5
        ),
        Like(
            user_id=14,
            story_id=9,
            count=2
        ),

        Like(
            user_id=14,
            story_id=14,
            count=8
        ),
        Like(
            user_id=14,
            story_id=15,
            count=9
        ),
        Like(
            user_id=14,
            story_id=16,
            count=3
        ),
        Like(
            user_id=15,
            story_id=17,
            count=9
        ),
        Like(
            user_id=15,
            story_id=18,
            count=4
        ),
        Like(
            user_id=15,
            story_id=19,
            count=9
        ),
        Like(
            user_id=16,
            story_id=20,
            count=2
        ),
        Like(
            user_id=17,
            story_id=20,
            count=6
        ),
        Like(
            user_id=17,
            story_id=14,
            count=8
        ),
        Like(
            user_id=17,
            story_id=13,
            count=3
        ),
        Like(
            user_id=18,
            story_id=13,
            count=3
        ),
        Like(
            user_id=18,
            story_id=4,
            count=1
        ),
        Like(
            user_id=18,
            story_id=19,
            count=3
        ),
        Like(
            user_id=19,
            story_id=17,
            count=2
        ),
        Like(
            user_id=19,
            story_id=16,
            count=2
        ),
        Like(
            user_id=19,
            story_id=20,
            count=3
        ),
        Like(
            user_id=19,
            story_id=15,
            count=1
        ),
        Like(
            user_id=19,
            story_id=10,
            count=1
        ),
        Like(
            user_id=20,
            story_id=13,
            count=2
        )]
    for like in likes:
        db.session.add(like)

    db.session.commit()


def undo_likes():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.likes RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM likes")

    db.session.commit()
